image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

otp-elixir:
  only:
    - main
  stage: build
  script:
    - docker build --pull --build-arg OTP_VER=23.3 --build-arg ELIXIR_VER=1.11.3 -t $CI_REGISTRY_IMAGE:otp-23.3-elixir-1.11.3-$CI_COMMIT_SHORT_SHA otp_elixir
    - docker tag $CI_REGISTRY_IMAGE:otp-23.3-elixir-1.11.3-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:otp-23.3-elixir-1.11.3-latest
    - docker push $CI_REGISTRY_IMAGE:otp-23.3-elixir-1.11.3-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:otp-23.3-elixir-1.11.3-latest
