name: otp-elixir image

on:
  push:
    branches: 
     - main 
     - dev/rust-cargo

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/$( echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' )/rust-cargo-builder:${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: docker buildx build --tag ${{ env.IMAGE_NAME }} --platform linux/amd64 ./rust-cargo
      - name: push the image
        run: docker push ${{ env.IMAGE_NAME }}
  build-arm64:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/$( echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' )/rust-cargo-builder:${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: docker buildx build --tag ${{ env.IMAGE_NAME }} --platform linux/arm64 ./rust-cargo
      - name: push the image
        run: docker push ${{ env.IMAGE_NAME }}
  build-armv7:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/$( echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' )/rust-cargo-builder:${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: docker buildx build --tag ${{ env.IMAGE_NAME }} --platform linux/arm/v7 ./rust-cargo
      - name: push the image
        run: docker push ${{ env.IMAGE_NAME }}
