name: rust-cargo image

on:
  push:
    branches: 
     - main 
     - dev/rust-cargo

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/$( echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' ):rust-cargo-builder_${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build \
            --tag ${{ env.IMAGE_NAME }} \
            --platform linux/amd64,linux/arm64 \
            --output 'type=image,push=true' \
            ./rust-cargo
